#!/bin/bash

set -e

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.
# See https://gist.github.com/rossf7/664dc1eb02f514993c7215d37058965c and
# https://docs.docker.com/docker-cloud/builds/advanced/

BUILD_ARCH=${DOCKER_TAG}
if [[ $BUILD_ARCH == *"_"* ]]
then
    BUILD_ARCH=$(echo "$BUILD_ARCH" | cut -d_ -f2)
else
    BUILD_ARCH="amd64"
fi

echo "Build hook running"
docker build \
             --file "${DOCKERFILE_PATH}"\
             --build-arg QEMU_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || ([ "${BUILD_ARCH}" == "arm64" ] && echo "aarch64") || echo "0") \
             --build-arg IMAGE_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "arm32v7/debian:buster" || ([ "${BUILD_ARCH}" == "arm64" ] && echo "arm64v8/debian:buster") || ([ "${BUILD_ARCH}" == "i386" ] && echo "i386/debian:buster") || echo "debian:buster") \
             --build-arg ARCH=${BUILD_ARCH} \
             --tag "${IMAGE_NAME}" \
             .
