name: Docker

on:
  push:
    branches:
      - 'latest'
      - '2.4.x'
      - '2.5.x'
  workflow_dispatch:

env:
  PLATFORMS: 'linux/amd64,linux/arm64,linux/i386,linux/armhf'
  TARGET_IMAGE_NAME: "urbackup-client"
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Set environmental variables"
        run: |
          echo "TARGET_IMAGE=${{secrets.DOCKERHUB_USERNAME}}/${TARGET_IMAGE_NAME}" >> $GITHUB_ENV
          echo "PLATFORMS=${PLATFORMS}" >> $GITHUB_ENV
      -  
        name: Check value
        id: target
        run: |
          echo "${{ env.TARGET_IMAGE }}" 
          echo "${{ env.PLATFORMS }}" 
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          # images: ${{ env.GITHUB_ACTOR}}/${{ env.GITHUB_REF_NAME }}
          images:  "${{ env.TARGET_IMAGE }}"
          # generate Docker tags based on the following events/attributes
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
